### ISSUE TITLE
keybindings to cut/copy/paste to/from clipboard

### ISSUE THREAD

**Issue by lordlabakdas** [avendael/atomic-emacs#103] opened 2016-04-25 12:38 UTC
Is there a keybinding for clipboard pastes from external sources such as the browser....atomic-emacs supports local cut/copy paste using regular emacs keybindings but not able to paste stuff from outside (without using the `right click mouse->paste`)

The way Emacs seems to handle it is through `M-x clipboard-yank` and `M-x clipboard-kill-region`.

**Comment by lordlabakdas** [comment] 2016-04-28 11:30
update: am able to copy text from atom to outside, and have updated the title to reflect this. The issue is with copying text from external sources to atom buffer.

**Comment by oggy** [comment] 2016-04-28 17:05
Which OS are you on? What do you see in the key binding resolver (cmd-. on mac) when you use the standard OS paste key (e.g. cmd-v on mac)?

**Comment by lordlabakdas** [comment] 2016-04-28 19:28
Ubuntu 14.04
On the key binding resolver and pressing `Ctrl-v`, the first 2 rows I see are
![image](https://cloud.githubusercontent.com/assets/1252659/14898637/606f6fba-0d4d-11e6-8cb8-cb5596f910e7.png)

**Comment by oggy** [comment] 2016-06-18 22:53
Sorry for the slow response here.

That explains it, though: the problem is that emacs' ctrl-v (scroll-up) conflicts with what you'd expect of a regular Linux desktop app (paste). I just tested with Emacs on Ubuntu (16.04), and it too favors scroll-up for ctrl-v, so I'm inclined to keep this behavior, at least as the default.

If you're just after direct a substitute for `M-x clipboard-yank`, you can do `alt-x core:paste`.

If you want to permanently override `ctrl-v` to the Atom default, you can add this to your personal keymap:

```
'atom-text-editor:not(.autocomplete-active):not(.mini)':
  'ctrl-v': 'core:paste'
```

**Comment by MartyGentillon** [comment] 2016-07-21 07:23
In my experience, in current versions of Emacs, when I cut or copy something in another program, it is inserted at the top of the kill ring, so C-y pastes it.  The kill ring here needs to work the same way.

**Comment by k1-hedayati** [comment] 2016-09-02 18:55
I agree with @MartyGentillon
Even when I start emacs with `emacs -Q` it integrates with system clipboard and I can copy and paste text from other apps to emacs (and vice vesa) seamlessly.

@oggy please consider adding this feature to `atomic-emacs`

**Comment by MartyGentillon** [comment] 2017-04-21 04:17
Tomorrow I should have a pull request for this.

**Comment by MartyGentillon** [comment] 2017-04-21 21:17
An initial implementation https://github.com/avendael/atomic-emacs/pull/130.  There are a couple concerns: first, when yanking to multiple cursors, a multi-line system clipboard should be split between the cursors based on lines.  (The current behavior is similar to my complaint in https://github.com/sublime-emacs/sublemacspro/issues/176)  Second, I am not certain that the "kill-ring per cursor" design is good.  It might be better to have one unified kill ring that is aware of multiple cursors, and multiple cursor yanks.

**Comment by MartyGentillon** [comment] 2017-05-17 07:26
So, the basic feature is now available.  Todos include possibly rethinking the kill-ring-per-cursor feature such that cuts from other programs integrate the way they would with the normal cut / paste feature (specifically where if you paste two lines of text with two cursors, each line goes to one cursor.)

**Comment by oggy** [comment] 2017-07-28 20:45
Closing this, as the requested functionality is there now - thanks @MartyGentillon .

**Closed by oggy** 2017-07-28 20:45 UTC

**Comment by dostrander** [comment] 2018-04-23 14:12
Just found atomic-emacs from this issue. Thanks for having a fix for one of my biggest complaints of atom.

**Comment by ifq** [comment] 2022-03-29 08:16
Hi,
I'm using version 0.15 right now, and the external copy doesn't insert into the kill ring. Am I missing something?
