### ISSUE TITLE
ctrl-n skips lines

### ISSUE THREAD

**Issue by mndrix** [avendael/atomic-emacs#34] opened 2014-12-16 22:31 UTC
I'm using atomic-emacs 0.3.5 with Atom 0.158.0 on OS X 10.10.1

  * press ctrl-n to move to the next line
  * disable atomic-emacs package
  * enable atomic-emacs package
  * pressing ctrl-n now moves two lines (skipping one line)
  * disable then enable again; ctrl-n now moves three lines (skipping two lines)

I have to run "Window: Reload" to get back to normal behavior.

**Comment by avendael** [comment] 2015-01-03 16:11
Thanks for the inputs everyone, it will help me debug the cause of this issue.

**Comment by avendael** [comment] 2015-01-03 17:08
Ok, figured out why it's happening.

```
  previousLine: (event) ->
    if atom.workspaceView.find('.fuzzy-finder').view() or
       atom.workspaceView.find('.command-palette').view()
      debugger # After activating the fuzzy finder or the command palette, all subsequent calls to this will trigger the debugger
      event.abortKeyBinding()

    @editor.moveCursors (cursor) ->
      cursor.moveUp()
```

The lines above are there to exempt some views from atomic emacs keybindings, otherwise, those views won't have an up/down keybinding at all.

I'll be pushing a fix shortly ;)

**Comment by avendael** [comment] 2015-01-03 17:27
Fixed by d92c41a748e5f12c727fc472d0e34e557c7a2693. Apparently, those lines aren't needed anymore. Please update to `0.3.6` :)

**Closed by avendael** 2015-01-03 17:27 UTC

**Comment by bohlander** [comment] 2015-01-14 23:31
This appears to be happening again on version 0.170.0 of Atom

**Comment by deanmalmgren** [comment] 2015-01-15 11:53
@bohlander looks like a new issue #37 is tracking this
